version: '3.2'

services:

  redis:
    image: "redis:alpine"
    command: redis-server
    expose:
     - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  server:
    build: . 
    ports:
      - "8080:8080"
    depends_on:
      - redis
      
volumes:
  redis-data:
  redis-conf: